#!/bin/bash

# Parse env
env=`cat env|grep -o "^[^#]*"`
update_env=""
create_env=""
for e in $env; do 
    update_env="$update_env --env-add $e"
    create_env="$create_env -e $e"
done

# Load conf
source conf

function create {
    docker service create \
     --with-registry-auth \
     --name $name \
     $create_env \
     $create_args \
     $image
}

function update {
    docker service update \
     --with-registry-auth \
     --image $image \
     $update_args \
     $name
}

function _ps {
    docker service ps $name
}

case $1 in
    ps)
     watch -n 1 $0 _ps
     ;;
    _ps)
     _ps
     ;;
    up)
     create 2>/dev/null && "Creating $name" || echo "Updating $name"
     update
     $0 ps
     ;;
    *)
     echo "Usage $0 [up|ps]"
     ;;
esac