#!/bin/bash

# Get Script dir
# http://stackoverflow.com/questions/59895
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
      DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
      SOURCE="$(readlink "$SOURCE")"
      [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# .git
GIT_DIR=$PWD/.git
if [ ! -d $GIT_DIR ] ;then
    if [ "$1" != init ] ;then
       echo "run $0 init"
       exit 1
    else
       mkdir -vp $GIT_DIR
       exit 0
    fi
fi

# SSH Key file
SSH_KEY_FILE=$GIT_DIR/key
SSH_KEY_FILE_PUB=$GIT_DIR/key.pub

# SSH GIT Use key
export GIT_SSH_COMMAND="ssh -i $SSH_KEY_FILE" 

# src dir
SRC_DIR=${GIT_DIR}/data/src
[ ! -d $SRC_DIR ] && SRC_DIR=$GIT_DIR

#--------------------------------------------------------------------------------
# GIT Command
#--------------------------------------------------------------------------------
function _git() {
    pushd $SRC_DIR
        git "$@"
    popd
}

#--------------------------------------------------------------------------------
# push Command
#--------------------------------------------------------------------------------
function _push() {
    _git add --all
    _git commit -m "banian"
    _git push
}

#--------------------------------------------------------------------------------
# pull Command
#--------------------------------------------------------------------------------
function _pull() {
    _git pull
}

#--------------------------------------------------------------------------------
# key Command
#--------------------------------------------------------------------------------
function _key() {
    if [ ! -f $SSH_KEY_FILE ] ; then
        ssh-keygen -t rsa -N "" -f $SSH_KEY_FILE -C "`uname -n`"
    else
        echo SSH key already exists!
    fi 
    cat $SSH_KEY_FILE_PUB
}

#--------------------------------------------------------------------------------

case "$1" in
    git) 
        shift
        _git $@
    ;;
    push)
        _push
    ;;
    pull)
        _pull
    ;;
    key)
        _key
    ;;
    *)
        echo "Usage: $0 [init|git|key|deploy|update]"
    ;;
esac